# Generated by Django 3.1.4 on 2020-12-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fav_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.BigIntegerField(null=True)),
                ('statusid', models.BigIntegerField(null=True)),
                ('supid', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mainsignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.TextField(null=True)),
                ('fname', models.TextField(max_length=200, null=True)),
                ('mname', models.TextField(max_length=200, null=True)),
                ('lname', models.TextField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='img')),
                ('image1', models.ImageField(null=True, upload_to='img')),
                ('image2', models.ImageField(null=True, upload_to='img')),
                ('gender', models.TextField(max_length=200, null=True)),
                ('dobdate', models.DateField(null=True)),
                ('sd', models.TextField(max_length=200, null=True)),
                ('age', models.TextField(max_length=200, null=True)),
                ('height', models.TextField(max_length=200, null=True)),
                ('education', models.TextField(max_length=500, null=True)),
                ('job', models.TextField(max_length=500, null=True)),
                ('cname', models.TextField(max_length=200, null=True)),
                ('sname', models.TextField(max_length=200, null=True)),
                ('dname', models.TextField(max_length=200, null=True)),
                ('phno1', models.BigIntegerField(null=True)),
                ('phno2', models.BigIntegerField(null=True)),
                ('religion', models.TextField(max_length=200, null=True)),
                ('rashi', models.TextField(max_length=200, null=True)),
                ('income', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Multiimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='imgmulti')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=200, null=True)),
                ('lname', models.TextField(max_length=200, null=True)),
                ('gender', models.TextField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phno1', models.BigIntegerField(null=True)),
                ('password', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
