# Generated by Django 3.0.6 on 2020-10-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=200, null=True)),
                ('lname', models.TextField(max_length=200, null=True)),
                ('gender', models.TextField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='cname',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='dname',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='dobdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='education',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='gender',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='job',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='mname',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='phno1',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='phno2',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='sd',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='sname',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mainsignup',
            name='fname',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mainsignup',
            name='lname',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
