# Generated by Django 3.1.4 on 2020-12-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav_list',
            name='heartcolor',
            field=models.TextField(default='hearto'),
        ),
    ]
