# Generated by Django 3.0.6 on 2020-10-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201020_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsignup',
            name='image',
        ),
    ]
