# Generated by Django 3.0.6 on 2020-10-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_mainsignup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsignup',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
