# Generated by Django 3.1.4 on 2020-12-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201204_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsignup',
            name='hid',
            field=models.TextField(null=True),
        ),
    ]
