# Generated by Django 3.1.4 on 2021-01-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mainsignup_hid'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='otp',
            field=models.TextField(max_length=6, null=True),
        ),
    ]
