# Generated by Django 3.0.6 on 2020-11-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mainsignup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsignup',
            name='sid',
            field=models.BigIntegerField(null=True),
        ),
    ]
