# Generated by Django 3.0.6 on 2020-11-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mainsignup_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsignup',
            name='sid',
            field=models.TextField(null=True),
        ),
    ]
