# Generated by Django 3.0.6 on 2020-11-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201107_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='phno1',
            field=models.BigIntegerField(null=True),
        ),
    ]
