# Generated by Django 3.0.6 on 2020-11-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_signup_phno1'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsignup',
            name='image1',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='image2',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='income',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='rashi',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainsignup',
            name='religion',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mainsignup',
            name='height',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
