# Generated by Django 3.0.6 on 2020-11-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201127_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='imgmulti')),
            ],
        ),
        migrations.RemoveField(
            model_name='mainsignup',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='mainsignup',
            name='image2',
        ),
    ]
