# Generated by Django 3.0.6 on 2020-11-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201128_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsignup',
            name='image1',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='mainsignup',
            name='image2',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
