# Generated by Django 3.0.6 on 2020-11-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_fav_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav_list',
            name='supid',
            field=models.BigIntegerField(null=True),
        ),
    ]
